name: Run Ultroid With UltroidCli On Github Actions
on:
  schedule:
    - cron: "0 */6 * * *"
  push:
    branches:
    - dev
  workflow_dispatch:


env:
  api_id: 21699423
  api_hash: 2efa2aebc2bbd14cf9adffadea314fc9
  session: VtsOKgBu73ZA2vHf4gEUAYhMkWKIqKtNqtZMXaYEIhecIHpizIO2DhVncZb8pw-SuhECXt829g8WAVP1y39jPE4NDXyQs_D36B-apV13XkZfAJxGSDM6LD1Pi6s29q_HtjPsS5UMode_kHg6-y1fB0sM8tHpxDVF4B6pzZsvjyA3yD1fx11ci6Q8zdjKnVQT46JinByGbqnXReHLE4TS7XsOU904OXPjACaMfhXQe-RlFWXGmKgQlE2DwULU4ja8FVJUKFP7aROGURCOxlduBYtG9ZhILrxLgfP-0hq9Aq9W1bLjqfuVXnqVZb9WqB5oVArIpLJQ9XoLw6GGhT_UwP3nhkaQg8=
  redis_uri: redis-19908.c262.us-east-1-3.ec2.cloud.redislabs.com:19908
  redis_password: Q04JFcHni03FKFmw1WlfTsO92nXkxwNK
  database_url: ${{ secrets.database_url }}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cancel Duplicate Workflows
        uses: styfle/cancel-workflow-action@0.9.0
        with:
            all_but_latest: true
            access_token: ${{ github.token }}
      - name: Run With UltroidCli
        continue-on-error: true
        uses: ./
